version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 30
    labels:
      - 'dependencies'
      - 'npm'
    versioning-strategy: auto
    ignore:
      - dependency-name: "npm"
        versions: ["<7.0.0", ">=11.0.0"]

  - package-ecosystem: 'npm'
    directory: '/apps/backend'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
      - 'npm'
      - 'backend'
    ignore:
      - dependency-name: "npm"
        versions: ["<7.0.0", ">=11.0.0"]

  - package-ecosystem: 'npm'
    directory: '/packages/db'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
      - 'npm'
      - 'db'
    ignore:
      - dependency-name: "npm"
        versions: ["<7.0.0", ">=11.0.0"]