version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 30
    labels:
      - 'dependencies'
      - 'npm'
    versioning-strategy: auto

  - package-ecosystem: 'npm'
    directory: '/apps/backend'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
      - 'npm'
      - 'backend'

  - package-ecosystem: 'npm'
    directory: '/packages/db'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
      - 'npm'
      - 'db'
