version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'cron'
      cron: '30 9 * * *'
    open-pull-requests-limit: 30
    labels:
      - 'dependencies'
      - 'npm'
    versioning-strategy: auto

  - package-ecosystem: 'npm'
    directory: '/apps/backend'
    schedule:
      interval: 'cron'
      cron: '30 9 * * *'
    labels:
      - 'dependencies'
      - 'npm'
      - 'backend'

  - package-ecosystem: 'npm'
    directory: '/packages/db'
    schedule:
      interval: 'cron'
      cron: '30 9 * * *'
    labels:
      - 'dependencies'
      - 'npm'
      - 'db'
